spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3307/sport_ai?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: Nhy6%tgb
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/**/*-schema.sql
    data: classpath*:sql/**/*-data.sql
    initialize: false

crud-plus:
  features:
    - eav
    - saas
    - tag

logging:
  level:
    root: info
  file: /logs/trace.log