###
@Endpoint = http://localhost:8080


### 图标列表
GET {{Endpoint}}/api/adm/frontIcon/frontIcons


### 图标列表
GET {{Endpoint}}/api/adm/frontIcon/frontIcons/2

### 新建图标
POST {{Endpoint}}/api/adm/frontIcon/frontIcons
content-type: application/json

{
    "icon":"/1003.jpg",
    "name":"测试图标",
    "extra":{
        "tags":"[{id:7},{id:5}]"
    },
    "describe":"描述"
}


### 图标列表
GET {{Endpoint}}/api/adm/frontIcon/frontIcons?tagName=动物