@endpoint=http://localhost:8080
@service=http://app1.console.smallsaas.cn:8001

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzNzA2MDA1LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTYyOTgwMDV9.nH3W8nkLMzrBp_VybRJ-ZnNjCG96RqD5a6-HikifXV9hQ618btKd8MGxoPf2XIroEzDc4Gj4JoVKk7dSBoB0zA

@A_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE4IiwidXNlcklkIjoiNiIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxMTAsImp0aSI6IjYiLCJzdWIiOiJBLTEiLCJleHAiOjE2NTYyOTgxMTB9.YN-_CKUKkWeLVnqNgfA3QHbKlI6kfr0-SK17X7akfhx25QMx-auwO8BnIDrFIqvAkOD3rZ251nWos3HrudZtow

@A_2token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE5IiwidXNlcklkIjoiNyIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0yIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTM3MDYxNTEsImp0aSI6IjciLCJzdWIiOiJBLTIiLCJleHAiOjE2NTYyOTgxNTF9.N_yWlEwVcqkdC6HRPskPrBYiiSW8TyL9a3uyWECmDUTVZxkUYcIXxuMUQwwgdjSdWUiIEd_Hj1Eup7LfjWs8yg

@A_1_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjIyIiwidXNlcklkIjoiOCIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xLTEiLCJ1c2VyVHlwZSI6MCwiZGV2VXNlclR5cGUiOjAsImJVc2VyVHlwZSI6IlNZU1RFTSIsImJVc2VySWQiOjAsImlhdCI6MTY1MzcwNjE3MywianRpIjoiOCIsInN1YiI6IkEtMS0xIiwiZXhwIjoxNjU2Mjk4MTczfQ.jQo-SxSEimkRJ2YqSIhsHaX7w8NQZ46J5ub8P6mYcQOFm3loYqi-dxxhtbO_-irHHvuc9sd2Zn9CrlnzXOJvmw


##公告列表查询
### 超级管理员查看
GET {{service}}/api/cms/notice/notices
Authorization:{{adminToken}}

### 用户A-1 用户级别为A-1
GET {{endpoint}}/api/cms/notice/notices
Authorization:{{A_1token}}

### A-2
### 用户A-2 用户级别为A-2 和A-1同级别
GET {{endpoint}}/api/cms/notice/notices
Authorization:{{A_2token}}

### 用户为A-1-1 用户级别为A-1-1 在A-1级别下
GET {{endpoint}}/api/cms/notice/notices
Authorization:{{A_1_1token}}


### 添加公告
POST {{endpoint}}/api/cms/notice/notices
Content-Type:application/json
Authorization:{{A_2token}}
{
    "author": "admin",
    "content": "部分库存信息有误，各负责人请检查下数据",
    "enabled": 2,
    "endDate": "0",
    "endTime": "2019-10-01 09:06:48",
    "isEnd": "end",
    "sortNum": 2,
    "title": "内部公告",
    "type": "Internal",
    "updateTime": null
}

### 查看公告
GET {{endpoint}}/api/cms/notice/notices/1196596850284810241
Authorization:{{A_2token}}


### 修改公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473
Authorization:{{A_2token}}
Content-Type:application/json
{
    "content": "部分库存信息有误",
    "enabled": 2,
    "endDate": "0",
    "endTime": "2019-10-01 09:06:48",
    "isEnd": "end",
    "sortNum": 2,
    "title": "内部公告",
    "type": "Internal",
    "updateTime": null
}


### 删除公告
DELETE {{endpoint}}/api/cms/notice/notices/1529001196451561473
Authorization:{{A_2token}}

### 发布公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473/publish
Authorization:{{A_2token}}

### 下架公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473/deprecate
Authorization:{{A_2token}}

### 启用公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473/enable
Authorization:{{A_2token}}

### 停止公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473/disable
Authorization:{{A_2token}}


### 启用(或取消启用)公告
PUT {{endpoint}}/api/cms/notice/notices/1529001196451561473/switchEnabled
Authorization:{{A_2token}}

### 最新公告（必须是未过期，且已启用的。结果按有效时间倒序）
GET {{endpoint}}/api/cms/notice/notices/recent/notices
Authorization:{{A_1token}}


GET {{endpoint}}/api/cms/notice/notices/1529391175619112962
Authorization:{{adminToken}}